#!/usr/bin/env bash -e

if [ $# -eq 0 ]
  then
    echo "Usage: ./leksah-nix.sh GHCVER [UI] [--in-tmux] [LEKSAH_ARGS]"
    echo
    echo "  GHCVER    : ghc8107 or ghc98 (Gtk UI), ghc914 (web UIs)"
    echo "  UI        : gtk (default), warp, wkwebview or webkitgtk"
    echo "  --in-tmux : (web UIs) run leksah inside a tmux session so its own"
    echo "              output shows up as \"Terminal 0\" in leksah's Terminals pane"
    echo
    echo "Examples: ./leksah-nix.sh ghc98"
    echo "          ./leksah-nix.sh ghc914 wkwebview --verbosity=DEBUG"
    echo "          ./leksah-nix.sh ghc914 warp --in-tmux"
    echo
    echo "For details of other LEKSAH_ARGS run: ./leksah-nix.sh ghc98 gtk --help"
    exit 1
fi

# Remember the full invocation before we consume the arguments, so it can be
# echoed into the run log below.
INVOCATION="$0 $*"

GHCARG=$1
shift

# Optional UI selector (defaults to the Gtk UI).  Anything else is a LEKSAH_ARG.
UI=gtk
case "$1" in
    gtk|warp|wkwebview|webkitgtk) UI=$1; shift ;;
esac

# Pull the script's own --in-tmux flag out of the leksah arguments.
IN_TMUX=0
ARGS=()
for a in "$@"; do
    if [ "$a" = "--in-tmux" ]; then IN_TMUX=1; else ARGS+=("$a"); fi
done
set -- "${ARGS[@]}"

# Tee everything (build output + leksah's own stdout/stderr, including the
# leksah-server metadata logs) to a file under ~/.leksah so a run can be
# examined after the fact.  Truncated each run.
RUNLOGDIR="$HOME/.leksah"
mkdir -p "$RUNLOGDIR"
RUNLOG="$RUNLOGDIR/leksah-nix-$UI.log"
exec > >(tee "$RUNLOG") 2>&1
echo "Logging this run to $RUNLOG"
echo "Invocation: $INVOCATION"
echo "Parsed: GHCVER=$GHCARG UI=$UI IN_TMUX=$IN_TMUX LEKSAH_ARGS=[$*]"

# NIX_ARGS='--system x86_64-darwin'

# Match the build dir leksah itself uses (dist-ghc-<version>), so the build this
# script drives and leksah's own builds/metadata read the same place.  Querying
# the dev shell's GHC gives the exact version leksah was built with.
GHCNUMVER=$(nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --command ghc --numeric-version 2>/dev/null | tail -1)
BUILDDIR="dist-ghc-${GHCNUMVER:-$GHCARG}"
echo "Using build dir: $BUILDDIR"

# A self-contained rebuild script for `leksah-cmd rebuild-self`.  It runs inside
# the already-running leksah's dev-shell environment (cabal/ghc are already on
# PATH), so it calls cabal directly rather than re-entering `nix develop`.  Uses
# the same build dir + target leksah was launched with.
# Map the UI selector to its cabal executable target.  The classic GTK front
# end is exe:leksah-classic; the three native web front ends (wkwebview /
# webkitgtk / webview2) are now a single exe:leksah selected per-OS in the
# cabal file; warp is its own exe:leksah-warp.
case "$UI" in
    gtk)  EXE_TARGET="exe:leksah-classic" ;;
    warp) EXE_TARGET="exe:leksah-warp" ;;
    *)    EXE_TARGET="exe:leksah" ;;
esac
REBUILD_TARGET="$EXE_TARGET"
mkdir -p "$HOME/.leksah"
cat > "$HOME/.leksah/rebuild.sh" <<EOF
#!/bin/sh
# Generated by leksah-nix.sh; run by 'leksah-cmd rebuild-self'.  leksah is launched
# directly (not via 'cabal run'), so its environment is identical to the build
# environment — calling cabal directly here matches the loop's build config and
# stays incremental (no slow nested 'nix develop', no full rebuild).
cd "$(pwd)" || exit 1
exec cabal build --builddir "$BUILDDIR" $REBUILD_TARGET exe:ffcabal
EOF

# macOS: run the wkwebview front end from a real .app bundle so CFBundleName
# names it "Leksah" in the menu bar, the Dock and the ⌘-Tab switcher (an
# unbundled binary is named after the executable, "leksah-wkwebview").  The
# bundle is a thin wrapper: its executable is hard-linked to the freshly built
# binary on each launch (see launch_leksah below), and data files still come
# from the repo via leksah_datadir — so this stays a normal incremental dev
# loop, it just gives the process a proper bundle identity.
APPBUNDLE="$(pwd)/Leksah.app"
if [ "$UI" = "wkwebview" ]; then
    mkdir -p "$APPBUNDLE/Contents/MacOS" "$APPBUNDLE/Contents/Resources"
    cat > "$APPBUNDLE/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Leksah</string>
  <key>CFBundleDisplayName</key><string>Leksah</string>
  <key>CFBundleExecutable</key><string>leksah</string>
  <key>CFBundleIdentifier</key><string>org.leksah.leksah</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleShortVersionString</key><string>0.17.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>CFBundleIconFile</key><string>leksah</string>
</dict>
</plist>
PLIST
    # Prefer the macOS app icon (leksah glyph on a dark-grey gradient); fall
    # back to the plain logo.
    if [ -f osx/leksah-macapp.icns ]; then
        cp -f osx/leksah-macapp.icns "$APPBUNDLE/Contents/Resources/leksah.icns"
    elif [ -f osx/leksah.icns ]; then
        cp -f osx/leksah.icns "$APPBUNDLE/Contents/Resources/leksah.icns"
    fi
fi

if [ "$IN_TMUX" = "1" ] && [ "$UI" = "gtk" ]; then
    echo "Note: --in-tmux only applies to the web UIs; ignoring for gtk."
    IN_TMUX=0
fi

if [ "$IN_TMUX" = "1" ]; then
    # A tmux config matching the one leksah uses for its own terminals, so the
    # session leksah runs in shares it (no status bar, titles passed through,
    # the login shell).  Whoever starts the `leksah` socket server first wins,
    # so set it here.
    LOGIN_SHELL="$(dscl . -read "/Users/$(id -un)" UserShell 2>/dev/null | awk '{print $2}')"
    [ -z "$LOGIN_SHELL" ] && LOGIN_SHELL="$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f7)"
    [ -z "$LOGIN_SHELL" ] && LOGIN_SHELL="${SHELL:-/bin/bash}"
    CONF="${TMPDIR:-/tmp}/leksah.tmux.conf"
    cat > "$CONF" <<EOF
set -g status off
set -g set-titles on
set -g set-titles-string "#T"
set -g default-shell "$LOGIN_SHELL"
set -g mouse on
set -g history-limit 50000
EOF
    LOGFILE="$RUNLOGDIR/leksah-$UI.log"
fi

LEKSAH_EXIT_CODE=2

# Exit 2 => relaunch after rebuilding (in-IDE / rebuild-self); exit 3 =>
# `leksah-cmd restart --no-rebuild`: relaunch but skip the cabal build (and its
# `nix develop`), since rebuild-self already produced the binary.
while [ $LEKSAH_EXIT_CODE -eq 2 ] || [ $LEKSAH_EXIT_CODE -eq 3 ]; do
  SKIP_REBUILD=0
  [ "$LEKSAH_EXIT_CODE" -eq 3 ] && SKIP_REBUILD=1
  rm -f .ghc.environment.*
  mkdir -p bin

  if [ "$UI" = "gtk" ]; then
    # Gtk: install the binaries, then launch through the `launch-leksah` wrapper
    # (which sets up the Gtk runtime environment).
    if [ "$SKIP_REBUILD" != 1 ]; then
      nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --show-trace --command \
        cabal install --builddir "$BUILDDIR" --installdir bin/$GHCARG --overwrite-policy=always \
          exe:leksah-server exe:leksah-classic exe:leksahecho exe:vcswrapper exe:vcsgui exe:vcsgui-askpass \
          || read -n 1 -s -r -p "Build failed.  Press any key to attempt to run last built version."
    else
      echo "leksah-cmd restart --no-rebuild: skipping build, relaunching."
    fi
    rm -f .ghc.environment.*

    LEKSAH_EXIT_CODE=0
    PATH=$(pwd)/bin/$GHCARG:$PATH nix $NIX_ARGS run .?submodules=1#launch-leksah -- ./bin/$GHCARG/leksah-classic --develop-leksah "$@" \
      || LEKSAH_EXIT_CODE=$?
  else
    # Web UIs (warp/wkwebview/webkitgtk): leksah-server must be on PATH (for
    # metadata) and tmux is needed for persistent terminals — both come from the
    # dev shell.  With --develop-leksah leksah exits with code 2 when rebuilt
    # (in-IDE or via `leksah-cmd rebuild-self`), so this loop relaunches it.
    #
    # Build the helper exes AND the front end with one `cabal build` (one project
    # plan — `cabal install` would resolve a separate plan and rebuild the world),
    # symlink the helpers onto PATH, then launch the built binary DIRECTLY rather
    # than via `cabal run`.  Two reasons every cabal step shares the bin/$GHCARG
    # PATH prefix and we avoid `cabal run`:
    #   * cabal treats a different PATH as "configuration changed" and rebuilds
    #     everything, so the prefix must be identical across all cabal calls;
    #   * `cabal run` augments the launched app's PATH with build-tool dirs, which
    #     would make an in-app `cabal build` (rebuild-self) see a different config
    #     and rebuild everything.  Launching the binary directly keeps the app's
    #     environment identical to the build environment, so rebuild-self stays
    #     incremental.
    if [ "$SKIP_REBUILD" != 1 ]; then
      PATH=$(pwd)/bin/$GHCARG:$PATH nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --show-trace --command \
        bash -c '
          set -e
          bd="$1"; gd="$2"; tgt="$3"
          cabal build --builddir "$bd" exe:leksah-server exe:leksah-cmd exe:ffcabal "$tgt"
          mkdir -p "bin/$gd"
          ln -sf "$(cabal list-bin --builddir "$bd" exe:leksah-server)" "bin/$gd/leksah-server"
          ln -sf "$(cabal list-bin --builddir "$bd" exe:leksah-cmd)"    "bin/$gd/leksah-cmd"
          ln -sf "$(cabal list-bin --builddir "$bd" exe:ffcabal)"       "bin/$gd/ffcabal"
        ' _ "$BUILDDIR" "$GHCARG" "$EXE_TARGET" \
          || read -n 1 -s -r -p "Build failed.  Press any key to attempt to run last built version."
    else
      echo "leksah-cmd restart --no-rebuild: skipping build, relaunching."
    fi
    rm -f .ghc.environment.*

    # Launch the freshly-built binary directly, inside the dev shell, with the
    # data dir `cabal run` would have set (the package root).  `exec` so leksah's
    # exit code propagates (2 => rebuilt => relaunch).
    launch_leksah='
      bd="$1"; ui="$2"; tgt="$3"; shift 3
      export leksah_datadir="$(pwd)"
      bin="$(cabal list-bin --builddir "$bd" "$tgt")"
      if [ "$ui" = "wkwebview" ]; then
        # Run from the .app so [NSBundle mainBundle] is Leksah.app (correct name
        # everywhere).  cabal relinks a new inode each build, so refresh the
        # bundle executable (hard link; copy across volumes) every launch.  exec
        # so leksah'\''s exit code still drives the relaunch loop.
        macos="$(pwd)/Leksah.app/Contents/MacOS"
        ln -f "$bin" "$macos/leksah" 2>/dev/null || cp -f "$bin" "$macos/leksah"
        exec "$macos/leksah" --develop-leksah "$@"
      fi
      exec "$bin" --develop-leksah "$@"'

    LEKSAH_EXIT_CODE=0
    if [ "$IN_TMUX" = "1" ]; then
      # A persistent session (shown as "Terminal 0" in leksah) tails leksah's
      # own log.  Created once on the `leksah` socket; closing it just stops the
      # tail, not leksah.
      nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --command \
        tmux -L leksah -f "$CONF" new-session -A -d -s leksah-0 tail -n +1 -F "$LOGFILE" || true
      echo "Launching leksah-$UI; its output appears as \"Terminal 0\" inside leksah (log: $LOGFILE)"
      PATH=$(pwd)/bin/$GHCARG:$PATH nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --command \
        bash -c "$launch_leksah" _ "$BUILDDIR" "$UI" "$EXE_TARGET" "$@" > "$LOGFILE" 2>&1 \
        || LEKSAH_EXIT_CODE=$?
    else
      PATH=$(pwd)/bin/$GHCARG:$PATH nix $NIX_ARGS develop ".?submodules=1#$GHCARG" --show-trace --command \
        bash -c "$launch_leksah" _ "$BUILDDIR" "$UI" "$EXE_TARGET" "$@" \
        || LEKSAH_EXIT_CODE=$?
    fi

    if [ "$UI" = "warp" ] && [ $LEKSAH_EXIT_CODE -eq 2 ]; then
      echo "leksah-warp rebuilt — relaunching (reload http://127.0.0.1:3367/ when ready)"
    fi
  fi
done
