# link with shared libs
%bcond_without dynamic

%global ghc_pkg_deps ghc-utf8-string-devel,ghc-gtk-devel,ghc-glib-devel,ghc-binary-shared-devel,ghc-leksah-server-devel,ghc-regex-base-devel,ghc-regex-tdfa-devel

# ghc does not emit debug information
%global debug_package %{nil}

Name:           leksah
Version:        0.8.0.6
Release:        1%{?dist}
Summary:        Haskell IDE

Group:          System Environment/IDE
License:        GPL
URL:            http://hackage.haskell.org/package/%{name}
Source0:        http://hackage.haskell.org/packages/archive/%{name}/%{version}/%{name}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
# fedora ghc archs:
ExclusiveArch:  %{ix86} x86_64 ppc alpha
BuildRequires:  ghc
BuildRequires:  ghc-rpm-macros >= 0.7.0
%{?ghc_pkg_deps:BuildRequires:  %{ghc_pkg_deps}, %(echo %{ghc_pkg_deps} | sed -e "s/\(ghc-[^, ]\+\)-devel/\1-doc,\1-prof/g")}
BuildRequires:  ghc-gtksourceview2-devel <= 0.11.2
BuildRequires:  ghc-gtksourceview2-doc,ghc-gtksourceview2-prof
%description
@DESCRIPTION@


%prep
%setup -q


%build
%ghc_bin_build


%install
rm -rf $RPM_BUILD_ROOT
%ghc_bin_install
mkdir -p $RPM_BUILD_ROOT/usr/share/applications
install -p -m 644  linux/applications/leksah.desktop $RPM_BUILD_ROOT/usr/share/applications
mkdir -p $RPM_BUILD_ROOT/usr/share/icons/hicolor/48x48/apps
install -p -m 644  linux/icons/hicolor/48x48/apps/leksah_48x48.png $RPM_BUILD_ROOT/usr/share/icons/hicolor/48x48/apps
mkdir -p $RPM_BUILD_ROOT/usr/share/mime/application/
install -p -m 644  linux/applications/leksah.xml $RPM_BUILD_ROOT/usr/share/mime/application/

%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc LICENSE
%attr(755,root,root) %{_bindir}/%{name}
%attr(755,root,root) %{_datadir}/%{name}-%{version}
%attr(644,root,root) /usr/share/applications/%{name}.desktop
%attr(644,root,root) /usr/share/mime/application/%{name}.xml
%attr(644,root,root) /usr/share/icons/hicolor/48x48/apps/leksah_48x48.png

%changelog
* Sun Oct 10 2010 Lakshmi Narasimhan T V <lakshminaras2002@gmail.com> - 0.8.0.6-1
- initial packaging for Fedora automatically generated by cabal2spec-0.22.2
- Added desktop, mime and icon files

* Sun Oct 10 2010 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org> - 0.8.0.6-0
- initial packaging for Fedora automatically generated by cabal2spec-0.22.2
