%global pkg_name leksah

%bcond_with dynamic

# ghc does not emit debug information
%global debug_package %{nil}

%global ghc_pkg_deps ghc-utf8-string-devel,ghc-gtksourceview2-devel,ghc-gtk-devel,ghc-glib-devel,ghc-binary-shared-devel,ghc-leksah-server-devel,ghc-regex-base-devel,ghc-regex-tdfa-devel

Name:           leksah
Version:        0.8.0.6
Release:        1%{?dist}
Summary:        Haskell IDE

Group:          System Environment/IDE
License:        GPL
URL:            http://hackage.haskell.org/cgi-bin/hackage-scripts/package/%{name}
Source0:        http://hackage.haskell.org/packages/archive/%{name}/%{version}/%{name}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
ExclusiveArch:  %{ix86} x86_64 ppc alpha
BuildRequires : ghc >= 6.10.1, ghc-rpm-macros >= 0.2.5, ghc-gtk2hs-common >= 0.10.1,leksah-server == 0.8.0.6,haddock
%{?ghc_pkg_deps:BuildRequires:  %{ghc_pkg_deps}, %(echo %{ghc_pkg_deps} | sed -e "s/\(ghc-[^, ]\+\)-devel/\1-doc,\1-prof/g")}

Requires: atk, glibc, cairo, fontconfig, freetype, gtk2, glib2, gmp, gtksourceview2, pango, leksah-server == 0.8.0.6

%description
Leksah is an IDE for Haskell

%prep
%setup -q


%build
%cabal_configure --ghc
%cabal build


%install
%cabal_install
mkdir $RPM_BUILD_ROOT/usr/share/applications
cp linux/applications/leksah.desktop $RPM_BUILD_ROOT/usr/share/applications
mkdir -p $RPM_BUILD_ROOT/usr/share/icons/hicolor/48x48/apps
cp linux/icons/hicolor/48x48/apps/leksah_48x48.png $RPM_BUILD_ROOT/usr/share/icons/hicolor/48x48/apps

%clean
rm -rf $RPM_BUILD_ROOT

%post
gtk-update-icon-cache

%postun
gtk-update-icon-cache

%files
%defattr(-,root,root,-)
%doc LICENSE
%attr(755,root,root) %{_bindir}/%{name}
%attr(755,root,root) %{_datadir}/%{pkg_name}-%{version}
%attr(644,root,root) /usr/share/applications/%{pkg_name}.desktop
%attr(644,root,root) /usr/share/icons/hicolor/48x48/apps/leksah_48x48.png


%changelog
* Fri May 28 2010 Lakshmi Narasimhan <lakshminaras2002@gmail.com> - 0.8.0.6-1
- initial version for Fedora 13

* Wed May 26 2010 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org> - 0.8.0.6-0
- initial packaging for Fedora automatically generated by cabal2spec-0.21.3
