#!/usr/bin/env bash
# Stage everything the "Try leksah" page (leksah.github.io/try/) needs:
#   * the shared client-side bundles at the SITE ROOT (docs/website): cm6/,
#     xterm/, pics/, fonts/ — the app's generated CSS references /pics/… and
#     /fonts/… by absolute path, so these must sit at the root of the
#     deployed site;
#   * the demo-specific files next to this page (try/): the compiled leksah
#     (GHC JS backend) and the generated demo project tree.
#
# Usage: ./copy-assets.sh [path-to-built-leksah-js]
#   With no argument, builds the JS front end via nix first:
#     nix build '.?submodules=1#javascript-unknown-ghcjs:leksah:exe:leksah'
set -euo pipefail

cd "$(dirname "$0")"
SITE=..
REPO=../../..

# Shared bundles + assets at the site root, straight from the repo (the same
# files the native app reads from its datadir).
rm -rf "$SITE"/cm6 "$SITE"/xterm "$SITE"/pics "$SITE"/fonts
mkdir -p "$SITE"/cm6 "$SITE"/xterm "$SITE"/pics "$SITE"/fonts
cp "$REPO"/cm6/leksah-cm6.js "$SITE"/cm6/
cp "$REPO"/xterm/xterm.css "$REPO"/xterm/xterm.js "$REPO"/xterm/addon-*.js "$SITE"/xterm/
cp -R "$REPO"/pics/. "$SITE"/pics/
cp -R "$REPO"/fonts/. "$SITE"/fonts/

# xterm.css as page-seeded TEXT (window.leksahXtermCss): the app injects it
# via mainWidgetWithCss exactly as it does natively.  A plain <link> would be
# lost — mainWidgetWithCss rebuilds <head>, removing page stylesheet links.
python3 -c "
import json, pathlib
css = pathlib.Path('$SITE/xterm/xterm.css').read_text()
pathlib.Path('demo-xterm-css.js').write_text(
    '// Generated by copy-assets.sh from xterm/xterm.css.\n'
    'window.leksahXtermCss = %s;\n' % json.dumps(css))
"

# The demo project tree (window.leksahDemoFiles), next to the page.
python3 gen-demo-files.py

# The canned terminal tabs (window.leksahDemoTerminals) from terminals/*.ans.
python3 gen-demo-terminals.py

# Precomputed hover tooltips (window.leksahDemoHovers).  Off the critical
# path when hovers are already generated: querying haskell-language-server
# takes a while, so regenerate explicitly (gen-demo-hovers.py) when the
# terminal dumps or packed sources change; here only fail if missing.
[ -e demo-hovers.js ] || { echo "demo-hovers.js missing — run gen-demo-hovers.py (needs the dev shell)"; exit 1; }

# The compiled leksah.  The GHC JS backend links a `leksah.jsexe/`
# directory (all.js plus the emscripten-compiled C bits, clibs.wasm); stage
# its whole contents so the page can load all.js as leksah.js and the
# loader can fetch its wasm sibling.  A plain-file argument (or install
# layout) is handled too — the "binary" is then a JS program whose
# node-style hashbang first line is harmless in browsers (hashbang comments
# are standard ES2023).
if [ $# -ge 1 ]; then
  JS="$1"
else
  nix build "$REPO?submodules=1#javascript-unknown-ghcjs:leksah:exe:leksah" -o result-js
  JSEXE=$(find -L result-js -maxdepth 3 -type d -name "*.jsexe" | head -1)
  if [ -n "$JSEXE" ]; then JS="$JSEXE"; else JS=$(find -L result-js/bin -maxdepth 1 -type f | head -1); fi
fi
echo "Staging compiled leksah from: $JS"
if [ -d "$JS" ]; then
  rm -rf jsexe; mkdir jsexe
  cp -RL "$JS"/. jsexe/
  chmod -R u+w jsexe
  cp jsexe/all.js leksah.js
  # The loader resolves clibs.wasm relative to the page; keep a copy beside it.
  [ -e jsexe/clibs.wasm ] && cp jsexe/clibs.wasm clibs.wasm || true
else
  cp -L "$JS" leksah.js
  chmod +w leksah.js
fi

# Give the browser build an environment (HOME etc.) — see patch-rts.py.
python3 patch-rts.py leksah.js

echo "Done.  Serve with ./serve.sh and open http://127.0.0.1:8000/try/"
