#!/usr/bin/env bash
# Stage the site into docs/website for local serving (serve.sh) and the
# manual leksah.github.io mirror.
#
# The real work now lives in the `leksah-website` nix derivation
# (nix/website.nix), whose orchestration is Haskell: assemble-site.hs runs
# the generators (GenXtermCss/GenDemoFiles/GenDemoTerminals/PatchRts) against
# the two GHC-JS-backend cross builds (leksah + the sandpit breakout game)
# and emits the complete site root.  This wrapper builds it and rsyncs the
# result over docs/website — every staged/generated name is gitignored, so
# the working tree stays clean.
#
# Iterating on ONE generator without a nix rebuild still works: they are
# runghc scripts (boot libraries only) —
#   runghc -f "$(command -v ghc)" gen-demo-files.hs      (from try/)
# (the -f names the compiler: ghc914-sh's runghc shim dies without it), and
# patch-rts.hs / gen-xterm-css.hs / gen-demo-terminals.hs likewise.
# demo-hovers.js is committed and NOT regenerated by the derivation — run
# gen-demo-hovers.hs from the dev shell (needs haskell-language-server) when
# the packed sources or terminal dumps change.
set -euo pipefail

cd "$(dirname "$0")"
SITE=..
REPO=../../..

nix build "$REPO?submodules=1#leksah-website" -o result-site
echo "Staging site from: $(readlink result-site)"

# rsync (not cp): the store copy is read-only, and --chmod restores normal
# permissions on the way in.  No --delete — docs/website holds sources too.
rsync -a --copy-links --chmod=Du+rwx,Fu+rw "result-site/" "$SITE/"

echo "Done.  Serve with ./serve.sh and open http://127.0.0.1:8000/try/"
