#!/usr/bin/env python3
"""Generate demo-terminals.js (window.leksahDemoTerminals) for the demo page.

Each terminals/NN-name.ans is a captured tmux pane (ANSI escapes intact) that
becomes one static terminal tab in the demo: NN orders the tabs, name labels
them.  The dump is emitted base64 — exactly the payload LeksahTerm.write
takes, which is how IDE.Web.Widget.Terminal writes it into the xterm under
ghcjs (see IDE.Web.DemoTerminals).

An ordered ARRAY (not an object): the tab order must survive the JSON
round-trip into the Haskell side.  Session ids are "$d0", "$d1", … —
tmux-session-id-shaped (leading $, no colon: Main.hs paneKey splits tab keys
on the first colon).

BEL bytes are stripped so the canned dump can't ring the demo's attention
bell on load.

Line endings are normalised LF -> CRLF: `tmux capture-pane -p` joins lines
with bare LF, but xterm (like a real terminal) treats LF as "cursor down,
SAME column" — a real shell's tty does the LF->CRLF translation (onlcr) that
a raw dump never got, so without this every line starts where the previous
one ended and the output staircases across the pane.
"""
import base64
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
DUMPS = sorted((HERE / 'terminals').glob('[0-9][0-9]-*.ans'))
if not DUMPS:
    raise SystemExit('gen-demo-terminals.py: no terminals/NN-name.ans dumps found')

terms = []
for i, p in enumerate(DUMPS):
    data = p.read_bytes().replace(b'\x07', b'')
    data = data.replace(b'\r\n', b'\n').replace(b'\n', b'\r\n')
    name = p.stem.split('-', 1)[1]
    terms.append({
        'id': '$d%d' % i,
        'name': name,
        'b64': base64.b64encode(data).decode('ascii'),
    })

out = HERE / 'demo-terminals.js'
out.write_text('// Generated by gen-demo-terminals.py from terminals/*.ans\n'
               'window.leksahDemoTerminals = %s;\n'
               % json.dumps(terms, indent=1))
print('wrote %s (%d terminals: %s)'
      % (out.name, len(terms), ', '.join(t['name'] for t in terms)))
