#!/usr/bin/env python3
"""Pack the demo project into demo-files.js for the "Try leksah" page.

The browser build has no file system; IDE.Web.FS seeds an in-memory tree from
`window.leksahDemoFiles` (path -> contents).  This script builds that object
from the repo's sandpit/breakout sample plus a synthesized demo.lkshw
workspace (the JSON shape IDE.Workspaces.Writer reads; paths are relative to
the .lkshw's own directory).
"""
import json, os, sys

here = os.path.dirname(os.path.abspath(__file__))
repo = os.path.abspath(os.path.join(here, "..", "..", ".."))

demo_lkshw = {
    "activeComponent": "exe:breakout",
    "activePackFile": "breakout/breakout.cabal",
    "activeProjectFile": "cabal.project",
    "activeProjectKey": {"contents": {"pjCabalFile": "cabal.project"}, "tag": "CabalTool"},
    "name": "demo",
    "packageVcsConf": {},
    "projectFiles": ["cabal.project"],
    "projectKeys": [{"contents": {"pjCabalFile": "cabal.project"}, "tag": "CabalTool"}],
    "saveTime": "Thu Jan  1 00:00:00 UTC 2026",
    "version": 4,
}

files = {"/demo/demo.lkshw": json.dumps(demo_lkshw, indent=4)}

# The sample project: sandpit/breakout, rooted at /demo in the mock tree
# (plus the terminal demo's hover target — see demo_manifest.py).
sys.path.insert(0, here)
from demo_manifest import SOURCE_FILES as mapping
for src, dst in mapping.items():
    p = os.path.join(repo, src)
    if not os.path.exists(p):
        sys.exit(f"missing {p}")
    with open(p, encoding="utf-8") as f:
        files[dst] = f.read()

out = os.path.join(here, "demo-files.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("// Generated by gen-demo-files.py — the in-memory demo tree for the\n")
    f.write("// browser build (read once by IDE.Web.FS at startup).\n")
    f.write("window.leksahDemoFiles = ")
    json.dump(files, f, indent=1)
    f.write(";\n")
print(f"wrote {out} ({len(files)} files)")
