{-# LANGUAGE OverloadedStrings #-}
-- | Emit demo-xterm-css.js: xterm.css as page-seeded TEXT
-- (window.leksahXtermCss).  The app injects it via mainWidgetWithCss exactly
-- as it does natively; a plain <link> would be lost — mainWidgetWithCss
-- rebuilds <head>, removing page stylesheet links.
--
-- Called by copy-assets.sh:  runghc gen-xterm-css.hs ../xterm/xterm.css
module Main (main) where

import qualified Data.Text.Lazy as TL
import System.Environment (getArgs)

import DemoUtil

main :: IO ()
main = do
  args <- getArgs
  let cssPath = case args of { (p:_) -> p; [] -> "../xterm/xterm.css" }
  css <- readFileUtf8 cssPath
  writeFileUtf8 "demo-xterm-css.js" $
    "// Generated by copy-assets.sh from xterm/xterm.css.\n\
    \window.leksahXtermCss = "
    <> TL.toStrict (dumps Nothing (JStr css))
    <> ";\n"
