{-# LANGUAGE OverloadedStrings #-}
-- | Pack the demo project into demo-files.js for the "Try leksah" page.
--
-- The browser build has no file system; IDE.Web.FS seeds an in-memory tree
-- from @window.leksahDemoFiles@ (path -> contents).  This script builds that
-- object from the repo's sandpit/breakout sample plus a synthesized
-- demo.lkshw workspace (the JSON shape IDE.Workspaces.Writer reads; paths are
-- relative to the .lkshw's own directory).
--
-- Run from docs/website/try (needs runghc from the dev shell):
--   runghc gen-demo-files.hs
module Main (main) where

import Control.Monad (forM, unless)
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import System.Directory (doesFileExist)
import System.Exit (die)
import System.FilePath ((</>))

import DemoManifest (sourceFiles)
import DemoUtil

repoRoot :: FilePath
repoRoot = "../../.."

demoLkshw :: Value
demoLkshw = JObj
  [ ("activeComponent",   JStr "exe:breakout")
  , ("activePackFile",    JStr "breakout/breakout.cabal")
  , ("activeProjectFile", JStr "cabal.project")
  , ("activeProjectKey",  cabalKey)
  , ("name",              JStr "demo")
  , ("packageVcsConf",    JObj [])
  , ("projectFiles",      JArr [JStr "cabal.project"])
  , ("projectKeys",       JArr [cabalKey])
  , ("saveTime",          JStr "Thu Jan  1 00:00:00 UTC 2026")
  , ("version",           JInt 4)
  ]
  where
    cabalKey = JObj
      [ ("contents", JObj [("pjCabalFile", JStr "cabal.project")])
      , ("tag",      JStr "CabalTool")
      ]

main :: IO ()
main = do
  here <- doesFileExist "index.html"
  unless here $ die "gen-demo-files.hs: run from docs/website/try"
  packed <- forM sourceFiles $ \(src, dst) -> do
    let p = repoRoot </> src
    ok <- doesFileExist p
    unless ok $ die ("missing " ++ p)
    contents <- readFileUtf8 p
    pure (T.pack dst, JStr contents)
  let files = ("/demo/demo.lkshw", JStr (TL.toStrict (dumps (Just 4) demoLkshw))) : packed
      out = "demo-files.js"
  writeFileUtf8 out $
    "// Generated by gen-demo-files.hs — the in-memory demo tree for the\n\
    \// browser build (read once by IDE.Web.FS at startup).\n\
    \window.leksahDemoFiles = "
    <> TL.toStrict (dumps (Just 1) (JObj files))
    <> ";\n"
  putStrLn ("wrote " ++ out ++ " (" ++ show (length files) ++ " files)")
