{-# LANGUAGE OverloadedStrings #-}
-- | The core of gen-demo-terminals.hs, parameterized so the site derivation
-- (nix\/website.nix via assemble-site.hs) can run it from any CWD: generate
-- demo-terminals.js (@window.leksahDemoTerminals@) for the demo page.
--
-- Each terminals\/NN-name.ans is a captured tmux pane (ANSI escapes intact)
-- that becomes one static terminal tab in the demo: NN orders the tabs, name
-- labels them.  The dump is emitted base64 — exactly the payload
-- LeksahTerm.write takes, which is how IDE.Web.Widget.Terminal writes it into
-- the xterm under the JS backend (see IDE.Web.DemoTerminals).
--
-- An ordered ARRAY (not an object): the tab order must survive the JSON
-- round-trip into the Haskell side.  Session ids are \"$d0\", \"$d1\", … —
-- tmux-session-id-shaped (leading $, no colon: Main.hs paneKey splits tab
-- keys on the first colon).
--
-- BEL bytes are stripped so the canned dump can't ring the demo's attention
-- bell on load.  Line endings are normalised LF -> CRLF: @tmux capture-pane
-- -p@ joins lines with bare LF, but xterm (like a real terminal) treats LF
-- as "cursor down, SAME column" — a real shell's tty does the LF->CRLF
-- translation (onlcr) that a raw dump never got, so without this every line
-- starts where the previous one ended and the output staircases across the
-- pane.
module GenDemoTerminals (run) where

import qualified Data.ByteString as BS
import Data.Char (isDigit)
import Data.List (sort, isSuffixOf, intercalate, stripPrefix)
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import System.Directory (listDirectory)
import System.Exit (die)
import System.FilePath ((</>), dropExtension)

import DemoUtil

-- glob [0-9][0-9]-*.ans
isDump :: FilePath -> Bool
isDump f = case f of
  (a:b:'-':rest) -> isDigit a && isDigit b && ".ans" `isSuffixOf` rest
  _ -> False

bsReplace :: BS.ByteString -> BS.ByteString -> BS.ByteString -> BS.ByteString
bsReplace old new = go
  where
    go s = case BS.breakSubstring old s of
      (pre, rest)
        | BS.null rest -> pre
        | otherwise    -> pre <> new <> go (BS.drop (BS.length old) rest)

-- | @run termDir outJs@ — read @termDir\/NN-name.ans@ dumps, write @outJs@
-- (demo-terminals.js).
run :: FilePath -> FilePath -> IO ()
run termDir outJs = do
  names <- sort . filter isDump <$> listDirectory termDir
  case names of
    [] -> die ("GenDemoTerminals: no NN-name.ans dumps found in " ++ termDir)
    _  -> pure ()
  terms <- mapM readDump (zip [0 :: Int ..] names)
  let tabNames = map dumpName names
  writeFileUtf8 outJs $
    "// Generated by GenDemoTerminals from terminals/*.ans\n"
    <> "window.leksahDemoTerminals = "
    <> TL.toStrict (dumps (Just 1) (JArr terms))
    <> ";\n"
  putStrLn ("wrote " ++ outJs ++ " (" ++ show (length terms) ++ " terminals: "
            ++ intercalate ", " tabNames ++ ")")
  where
    dumpName f = case stripPrefix "-" (dropWhile isDigit (dropExtension f)) of
      Just n  -> n           -- stem after the first '-' (Python: stem.split('-', 1)[1])
      Nothing -> dropExtension f
    readDump (i, f) = do
      raw <- BS.readFile (termDir </> f)
      let noBel = BS.filter (/= 7) raw
          crlf = bsReplace "\n" "\r\n" (bsReplace "\r\n" "\n" noBel)
      pure $ JObj
        [ ("id",   JStr (T.pack ("$d" ++ show i)))
        , ("name", JStr (T.pack (dumpName f)))
        , ("b64",  JStr (b64encode crlf))
        ]
