{-# LANGUAGE OverloadedStrings #-}
-- | The core of gen-demo-files.hs, parameterized so the site derivation
-- (nix\/website.nix via assemble-site.hs) can run it from any CWD: pack the
-- demo project into demo-files.js for the "Try leksah" page.
--
-- The browser build has no file system; IDE.Web.FS seeds an in-memory tree
-- from @window.leksahDemoFiles@ (path -> contents).  The object is built
-- from the repo's sandpit\/breakout sample ('DemoManifest.sourceFiles') plus
-- a synthesized demo.leksah.json workspace (the JSON shape IDE.Ws.File
-- reads; paths are relative to the workspace file's own directory).
module GenDemoFiles (run) where

import Control.Monad (forM, unless)
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import System.Directory (doesFileExist)
import System.Exit (die)
import System.FilePath ((</>))

import DemoManifest (sourceFiles)
import DemoUtil

-- | The demo workspace: one cabal project rooted at the workspace file's own
-- directory (@\/demo@), described by the packed @cabal.project@, with
-- breakout's @exe:breakout@ active.  Everything the file names must also be
-- in 'DemoManifest.sourceFiles' — the browser has no other file system, and
-- project enumeration reads @cabal.project@ and each @.cabal@ through the
-- same mock tree (IDE.Web.FS's 'fsEffects').
demoWorkspace :: Value
demoWorkspace = JObj
  [ ("active",   JObj
      [ ("component", JObj [ ("kind", JStr "exe"), ("name", JStr "breakout") ])
      , ("package",   JStr "breakout/breakout.cabal")
      , ("project",   JStr ".")
      ])
  , ("name",     JStr "demo")
  , ("projects", JArr
      [ JObj [ ("file", JStr "cabal.project")
             , ("root", JStr ".")
             , ("type", JStr "cabal") ] ])
  , ("version",  JInt 1)
  ]

-- | @run repoRoot outJs@ — pack 'sourceFiles' (paths relative to
-- @repoRoot@) and the synthesized workspace into @outJs@ (demo-files.js).
run :: FilePath -> FilePath -> IO ()
run repoRoot outJs = do
  packed <- forM sourceFiles $ \(src, dst) -> do
    let p = repoRoot </> src
    ok <- doesFileExist p
    unless ok $ die ("GenDemoFiles: missing " ++ p)
    contents <- readFileUtf8 p
    pure (T.pack dst, JStr contents)
  let files = ( "/demo/demo.leksah.json"
              , JStr (TL.toStrict (dumps (Just 4) demoWorkspace)) ) : packed
  writeFileUtf8 outJs $
    "// Generated by GenDemoFiles — the in-memory demo tree for the\n"
    <> "// browser build (read once by IDE.Web.FS at startup).\n"
    <> "window.leksahDemoFiles = "
    <> TL.toStrict (dumps (Just 1) (JObj files))
    <> ";\n"
  putStrLn ("wrote " ++ outJs ++ " (" ++ show (length files) ++ " files)")
