{-# LANGUAGE OverloadedStrings #-}
-- | The core of gen-demo-files.hs, parameterized so the site derivation
-- (nix\/website.nix via assemble-site.hs) can run it from any CWD: pack the
-- demo project into demo-files.js for the "Try leksah" page.
--
-- The browser build has no file system; IDE.Web.FS seeds an in-memory tree
-- from @window.leksahDemoFiles@ (path -> contents).  The object is built
-- from the repo's sandpit\/breakout sample ('DemoManifest.sourceFiles') plus
-- a synthesized demo.lkshw workspace (the JSON shape IDE.Workspaces.Writer
-- reads; paths are relative to the .lkshw's own directory).
module GenDemoFiles (run) where

import Control.Monad (forM, unless)
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import System.Directory (doesFileExist)
import System.Exit (die)
import System.FilePath ((</>))

import DemoManifest (sourceFiles)
import DemoUtil

demoLkshw :: Value
demoLkshw = JObj
  [ ("activeComponent",   JStr "exe:breakout")
  , ("activePackFile",    JStr "breakout/breakout.cabal")
  , ("activeProjectFile", JStr "cabal.project")
  , ("activeProjectKey",  cabalKey)
  , ("name",              JStr "demo")
  , ("packageVcsConf",    JObj [])
  , ("projectFiles",      JArr [JStr "cabal.project"])
  , ("projectKeys",       JArr [cabalKey])
  , ("saveTime",          JStr "Thu Jan  1 00:00:00 UTC 2026")
  , ("version",           JInt 4)
  ]
  where
    cabalKey = JObj
      [ ("contents", JObj [("pjCabalFile", JStr "cabal.project")])
      , ("tag",      JStr "CabalTool")
      ]

-- | @run repoRoot outJs@ — pack 'sourceFiles' (paths relative to
-- @repoRoot@) and the synthesized workspace into @outJs@ (demo-files.js).
run :: FilePath -> FilePath -> IO ()
run repoRoot outJs = do
  packed <- forM sourceFiles $ \(src, dst) -> do
    let p = repoRoot </> src
    ok <- doesFileExist p
    unless ok $ die ("GenDemoFiles: missing " ++ p)
    contents <- readFileUtf8 p
    pure (T.pack dst, JStr contents)
  let files = ("/demo/demo.lkshw", JStr (TL.toStrict (dumps (Just 4) demoLkshw))) : packed
  writeFileUtf8 outJs $
    "// Generated by GenDemoFiles — the in-memory demo tree for the\n"
    <> "// browser build (read once by IDE.Web.FS at startup).\n"
    <> "window.leksahDemoFiles = "
    <> TL.toStrict (dumps (Just 1) (JObj files))
    <> ";\n"
  putStrLn ("wrote " ++ outJs ++ " (" ++ show (length files) ++ " files)")
