{-# LANGUAGE OverloadedStrings #-}
-- | The core of gen-xterm-css.hs, parameterized so the site derivation
-- (nix\/website.nix via assemble-site.hs) can run it against explicit paths:
-- emit xterm.css as page-seeded TEXT (@window.leksahXtermCss@).  The app
-- injects it via mainWidgetWithCss exactly as it does natively; a plain
-- @<link>@ would be lost — mainWidgetWithCss rebuilds @<head>@, removing
-- page stylesheet links.
module GenXtermCss (run) where

import qualified Data.Text.Lazy as TL

import DemoUtil

-- | @run cssPath outJs@ — read @cssPath@ (xterm.css), write @outJs@
-- (demo-xterm-css.js).
run :: FilePath -> FilePath -> IO ()
run cssPath outJs = do
  css <- readFileUtf8 cssPath
  writeFileUtf8 outJs $
    "// Generated by GenXtermCss from leksah/xterm/xterm.css.\n"
    <> "window.leksahXtermCss = "
    <> TL.toStrict (dumps Nothing (JStr css))
    <> ";\n"
